name = "Hat Kid Reloaded (Internal)" -- Edit this title depending on branch.
description = "The Overhaul update! So much to do, and so much to try!"
author = "Skylarr"
version = "3.0.0b16"

forumthread = ""

api_version = 10

dst_compatible = true

dont_starve_compatible = false
reign_of_giants_compatible = false

all_clients_require_mod = true 

icon_atlas = "modicon.xml"
icon = "modicon.tex"

server_filter_tags = {
"kid",
"hat",
"time",
"hatkid",
"a hat in time",
"hat kid",
"cute",
}

local null_options = {
	{ description = "", data = 0 }
}

-- Set some vars for config
local seg_time = 30
local total_day_time = seg_time*16

configuration_options =
{

	{
		name = "Character Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "hatkidbasehp",
		label = "Health",
		hover = "How much health Hat Kid will have.",
		options =
		{
			{description = "25", data = 25},
			{description = "50", data = 50},
			{description = "75", data = 75},
			{description = "100", data = 100},
			{description = "120", data = 120},
			{description = "130", data = 130},
			{description = "150 (Default)", data = 150},
			{description = "175", data = 175},
			{description = "200", data = 200},
			{description = "225", data = 225},
			{description = "250", data = 250},
			{description = "275", data = 275},				
			{description = "300", data = 300},
		},
		default = 150,
	},
	
	{
		name = "hatkidbasesanity",
		label = "Sanity",
		hover = "How much sanity Hat Kid will have.",
		options =
		{
			{description = "25", data = 25},
			{description = "50", data = 50},
			{description = "75 (Wes)", data = 75},
			{description = "100 (Low Norm)", data = 100},
			{description = "120 (Default)", data = 120},
			{description = "125", data = 125},
			{description = "150 (Average)", data = 150},
			{description = "175", data = 175},
			{description = "200 (High Norm)", data = 200},
			{description = "225", data = 225},
			{description = "250 (Wicker)", data = 250},
			{description = "275", data = 275},				
			{description = "300", data = 300},
		},
		default = 120,
	},
	
	{
		name = "hatkidbasehunger",
		label = "Hunger",
		hover = "How much hunger Hat Kid will have.",
		options =
		{
			{description = "25", data = 25},
			{description = "50", data = 50},
			{description = "75", data = 75},
			{description = "100", data = 100},
			{description = "105", data = 105},
			{description = "110", data = 110},
			{description = "115", data = 115},
			{description = "120 (Default)", data = 120},
			{description = "125", data = 125},
			{description = "130", data = 130},
			{description = "135", data = 135},
			{description = "140", data = 140},
			{description = "150", data = 150},
			{description = "175", data = 175},
			{description = "200", data = 200},
			{description = "225", data = 225},
			{description = "250", data = 250},
			{description = "275", data = 275},				
			{description = "300", data = 300},
			{description = "400", data = 400},
		},
		default = 120,
	},
	
	{
		name = "hatkidspeed",
		label = "Run Speed",
		hover = "How fast Hat Kid will go.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.1", data = 1.1},
			{description = "x1.2", data = 1.2},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
		},
		default = 1,
	},
	
	{
		name = "hatkiddamagedealt",
		label = "Damage Dealt",
		hover = "Hat Kid's damage multiplier",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.85", data = 0.85},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},
	
	{
		name = "hatkiddamagetaken",
		label = "Damage Taken",
		hover = "Hat Kid's damage taken multiplier",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.85", data = 0.85},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},

	
	
	{
		name = "hatkidbasesize",
		label = "Character Size",
		hover = "How big Hat Kid will be",
		options =
		{
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.85", data = 0.85},
			{description = "x0.9 (Default)", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 0.9,
	},
	
	{
		name = "hatkidrate",
		label = "Hunger Rate",
		hover = "How fast Hat Kid's hunger drains.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},
	
	{
		name = "hatkidnightdrain",
		label = "Night Drain",
		hover = "How much Hat Kid's sanity will be impacted by nighttime.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},

	{
		name = "hatkidsanitydrain",
		label = "Sanity Aura Drain",
		hover = "How much Hat Kid's sanity will be negatively impacted by auras.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},	

	{
		name = "hatkidsanitymult",
		label = "Sanity Mult",
		hover = "How much Hat Kid's sanity will be impacted by both positive and negative sources.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5 (Default)", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1.5,
	},	


	{
		name = "Kid's Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "kidhatdurability",
		label = "Durability",
		hover = "How long the Kid's Hat lasts. Durability goes down while the hat is being worn.",
		options =
		{
			{description = "Forever (Default)", data = false},
			{description = "30 seconds", data = 30},
			{description = "1 minute", data = 60},
			{description = "5 minutes", data = 5 * 60},
			{description = "10 minutes", data = 10 * 60},
			{description = "15 minutes", data = 15 * 60},
			{description = "30 minutes", data = 30 * 60},
			{description = "45 minutes", data = 45 * 60},
			{description = "60 minutes", data = 60 * 60},
			{description = "75 minutes", data = 75 * 60},
			{description = "90 minutes", data = 90 * 60},
			{description = "2 hours", data = 2 * 60 * 60},
			{description = "3 hours", data = 3 * 60 * 60},
			{description = "4 hours", data = 4 * 60 * 60},
			{description = "6 hours", data = 6 * 60 * 60},
			{description = "12 hours", data = 12 * 60 * 60},
			{description = "Forever (Default)", data = false},
		},
		default = false,
	},

	-- {
	-- 	name = "hatkidaurasize",
	-- 	label = "Sanity Aura Size",
	-- 	hover = "How big Hat Kid's sanity aura will be.",
	-- 	options =
	-- 	{
	-- 		{description = "Disabled", data = 0},
	-- 		{description = "Smol", data = 16},
	-- 		{description = "Small", data = 32},
	-- 		{description = "Medium", data = 64},
	-- 		{description = "Large (Default)", data = 128},
	-- 		{description = "Huge! (seriously)", data = 512},
			
	-- 	},
	-- 	default = 128,
	-- },

	-- {
	-- 	name = "hatkidaurarate",
	-- 	label = "Sanity Aura Rate",
	-- 	hover = "How powerful Hat Kid's sanity aura is, in sanity per minute",
	-- 	options =
	-- 	{
	-- 		{description = "1", data = 0.0167},
	-- 		{description = "1.5", data = 0.025},
	-- 		{description = "3 (Default)", data = 0.05},
	-- 		{description = "6", data = 0.1},
	-- 		{description = "15", data = 0.25},
	-- 		{description = "20", data = 0.334},
	-- 		{description = "30", data = 0.5},
	-- 		{description = "60", data = 1},
	-- 		{description = "120", data = 2},
	-- 		{description = "240", data = 4},
	-- 		{description = "600", data = 10},
	-- 	},
	-- 	default = 0.05,
	-- },

	{
		name = "Sprint Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "sprinthatdurability",
		label = "Durability",
		hover = "How long the sprinthat lasts while sprinting. Durabiltiy only decreases while sprinting.",
		options =
		{
			{description = "Forever (Default)", data = false},
			{description = "30 seconds", data = 30},
			{description = "1 minute", data = 60},
			{description = "5 minutes", data = 5 * 60},
			{description = "10 minutes", data = 10 * 60},
			{description = "15 minutes", data = 15 * 60},
			{description = "30 minutes", data = 30 * 60},
			{description = "45 minutes", data = 45 * 60},
			{description = "60 minutes", data = 60 * 60},
			{description = "75 minutes", data = 75 * 60},
			{description = "90 minutes", data = 90 * 60},
			{description = "2 hours", data = 2 * 60 * 60},
			{description = "3 hours", data = 3 * 60 * 60},
			{description = "4 hours", data = 4 * 60 * 60},
			{description = "6 hours", data = 6 * 60 * 60},
			{description = "12 hours", data = 12 * 60 * 60},
			{description = "Forever (Default)", data = false},
		},
		default = false,
	},

	{
		name = "sprinthatspeedmult",
		label = "Speed Multiplier",
		hover = "How much faster the Sprint Hat makes Hat Kid run.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.1", data = 1.1},
			{description = "x1.25", data = 1.25},
			{description = "x1.3", data = 1.3},
			{description = "x1.35 (Default)", data = 1.35},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
		},
		default = 1.35,
	},
	
	{
		name = "sprinthathungerburnrate",
		label = "Hunger Multiplier",
		hover = "How much faster the Sprint Hat makes Hat Kid starve, while running.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.67 (Default)", data = 1.67},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1.67,
	},

	{
		name = "sprinthatsfx",
		label = "Sprint SFX",
		hover = "Whether or not moving while wearing the sprint hat will produce a sound effect. It can be disabled if you find it annoying.",
		options =
		{
			{description = "Disabled", data = false},
			{description = "Enabled (Default)", data = true},
		},
		default = true,
	},

	{
		name = "Brewing Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "brewdurability",
		label = "Durability",
		hover = "How many uses the Brewing Hat has. One use per concoction brewed.",
		options =
		{
			{description = "Infinite", data = false},
			{description = "1", data = 1},
			{description = "3", data = 3},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "15", data = 15},
			{description = "20", data = 20},
			{description = "25", data = 25},
			{description = "30", data = 30},
			{description = "35", data = 35},
			{description = "40 (Default)", data = 40},
			{description = "45", data = 45},
			{description = "50", data = 50},
			{description = "55", data = 55},
			{description = "60", data = 60},
			{description = "70", data = 70},
			{description = "80", data = 80},
			{description = "90", data = 90},
			{description = "100", data = 100},
			{description = "150", data = 150},
			{description = "250", data = 250},
			{description = "500", data = 500},
			{description = "1000", data = 1000},
			{description = "Infinite", data = false},
		},
		default = 40,
	},
	
	{
		name = "brewcooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "4 Seconds (Default)", data = 4},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "12 Seconds", data = 12},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 4,
	},
	
	{
		name = "brewcharge",
		label = "Concoction Brewing Time",
		hover = "How long it takes for the concoction to brew before Hat Kid can throw it.",
		options =
		{
			{description = "No charge time", data = 0},
			{description = "1/4 of a Second", data = 0.25},
			{description = "1/2 of a Second", data = 0.5},
			{description = "3/4 of a Second", data = 0.75},
			{description = "1 Second (Default)", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "5 Seconds", data = 5},
		},
		default = 1,
	},
	
	{
		name = "brewslow",
		label = "Concoction Slowness",
		hover = "Hat Kid's speed multiplier while holding a concoction.",
		options =
		{
			{description = "-100%", data = 0},
			{description = "-90%", data = 0.1},
			{description = "-80%", data = 0.2},
			{description = "-75%", data = 0.25},
			{description = "-70%", data = 0.3},
			{description = "-60%", data = 0.4},
			{description = "-50%", data = 0.5},
			{description = "-40%", data = 0.6},
			{description = "-30%", data = 0.7},
			{description = "-25% (Default)", data = 0.75},
			{description = "-20%", data = 0.8},
			{description = "-10%", data = 0.9},
			{description = "No effect", data = 1},
			{description = "+10%", data = 1.1},
			{description = "+20%", data = 1.2},
			{description = "+30%", data = 1.3},
			{description = "+40%", data = 1.4},
			{description = "+50%", data = 1.5},
			{description = "+60%", data = 1.6},
			{description = "+70%", data = 1.7},
			{description = "+80%", data = 1.8},
			{description = "+90%", data = 1.9},
			{description = "+100%", data = 2},
		},
		default = 0.75,
	},
	
	{
		name = "brewdamage",
		label = "Concoction Explosion Damage",
		hover = "How much damage the thrown concoction's explosion will deal.",
		options =
		{
			{description = "1", data = 1},
			{description = "9", data = 9},
			{description = "14", data = 14},
			{description = "27", data = 27},
			{description = "34", data = 34},
			{description = "46", data = 46},
			{description = "51", data = 51},
			{description = "63", data = 63},
			{description = "72", data = 72},
			{description = "80", data = 80},
			{description = "89 (Default)", data = 89},
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "500", data = 500},
			{description = "KILLER QUEEN!!!", data = 999999, hover = "999,999"},
		},
		default = 89,
	},
	
	{
		name = "brewradius",
		label = "Concoction Explosion Radius",
		hover = "How big the thrown concoction's explosions will be. This value is mostly arbitrary, but still effective to the range.",
		options =
		{
			{description = "0 (Disabled)", data = 0},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3 (Default)", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8 (Very Large)", data = 8},
		},
		default = 3,
	},

	{
		name = "Ice Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "polardurability",
		label = "Durability",
		hover = "How many uses the Ice Hat has. One use per ground slam.",
		options =
		{
			{description = "Infinite", data = false},
			{description = "1", data = 1},
			{description = "3", data = 3},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "15", data = 15},
			{description = "20 (Default)", data = 20},
			{description = "25", data = 25},
			{description = "30", data = 30},
			{description = "35", data = 35},
			{description = "40", data = 40},
			{description = "45", data = 45},
			{description = "50", data = 50},
			{description = "55", data = 55},
			{description = "60", data = 60},
			{description = "70", data = 70},
			{description = "80", data = 80},
			{description = "90", data = 90},
			{description = "100", data = 100},
			{description = "150", data = 150},
			{description = "250", data = 250},
			{description = "500", data = 500},
			{description = "1000", data = 1000},
			{description = "Infinite", data = false},
		},
		default = 20,
	},
	
	{
		name = "polarcooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "4 Seconds (Default)", data = 4},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 4,
	},

	{
		name = "polarlevel",
		label = "Freeze Level",
		hover = "Sets which level of freeze the Ice Hat will use in it's radius. Each level is equivelant to 1 hit from the Ice Staff.",
		options =
		{
			{description = "1", data = 1},
			{description = "2 (Default)", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 2,
	},

	{
		name = "polartemp",
		label = "Temp Reduction",
		hover = "Determines how much the Ice Hat cools players inside the radius down by when activated.",
		options =
		{
			{description = "None", data = 0},
			{description = "-2.5", data = 2.5},
			{description = "-5", data = 5},
			{description = "-10", data = 10},
			{description = "-15", data = 15},
			{description = "-20 (Default)", data = 20},
			{description = "-25", data = 25},
			{description = "-30", data = 30},
			{description = "-35", data = 35},
			{description = "-40", data = 40},
			{description = "-50", data = 50},
			{description = "-60", data = 60},
			{description = "-70", data = 70},
			{description = "-80", data = 80},
			{description = "-90", data = 90},
			{description = "-100", data = 100},
		},
		default = 20,
	},

	{
		name = "polarradius",
		label = "Radius",
		hover = "How big the Ice Hat's freeze radius will be. This value is mostly arbitrary, but still effective to the range.",
		options =
		{
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6 (Default)", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
			{description = "11", data = 11},
			{description = "12", data = 12},
			{description = "13", data = 13},
			{description = "14", data = 14},
			{description = "15", data = 15},
			{description = "16 (Very Large)", data = 16},

		},
		default = 6,
	},

	{
		name = "Dweller Mask Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "dwellerdurability",
		label = "Durability",
		hover = "How long the Dweller Mask lasts while active. Nightmare Fuel refuels 1.5 minutes at all settings.",
		options =
		{
			-- nightmarefuel refules up to 180 regardless of this setting.
			{description = "Forever", data = false},
			{description = "1.5 minutes", data = 180},
			{description = "3 minutes", data = 180 * 2},
			{description = "4.5 minutes", data = 180 * 3},
			{description = "6 minutes (Default)", data = 180 * 4},
			{description = "7.5 minutes", data = 180 * 5},
			{description = "9 minutes", data = 180 * 6},
			{description = "10.5 minutes", data = 180 * 7},
			{description = "15 minutes", data = 180 * 10},
			{description = "30 minutes", data = 180 * 20},
			{description = "Forever", data = false},
		},
		default = 180 * 4,
	},
	
	{
		name = "dwellercooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "4 Seconds (Default)", data = 4},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 4,
	},
	
	-- 	{
	-- 	name = "dwelleractive",
	-- 	label = "Duration",
	-- 	hover = "How long the dweller mask can remain active. It can be cancelled early regardless of what this value is set to.",
	-- 	options =
	-- 	{
	-- 		{description = "1 Second", data = 1},
	-- 		{description = "5 Seconds", data = 5},
	-- 		{description = "10 Seconds", data = 10},
	-- 		{description = "15 Seconds", data = 15},
	-- 		{description = "20 Seconds", data = 20},
	-- 		{description = "30 Seconds (Default)", data = 30},
	-- 		{description = "45 Seconds", data = 45},
	-- 		{description = "60 Seconds", data = 60},
	-- 		{description = "90 Seconds", data = 90},
	-- 		{description = "2 Minutes", data = 120},
	-- 		{description = "3 Minutes", data = 180},
	-- 		{description = "4 Minutes", data = 240},
	-- 		{description = "5 Minutes", data = 300},
	-- 		{description = "10 Minutes", data = 600},
	-- 		{description = "15 Minutes", data = 900},
	-- 	},
	-- 	default = 30,
	-- },
	
	{
		name = "dwellerlinger",
		label = "Linger Duration",
		hover = "How long the nightvision effect will linger for.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "4 Seconds (Default)", data = 4},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
		},
		default = 4,
	},

	{
		name = "dwellerradius",
		label = "Radius",
		hover = "How big the Dweller Mask's effect radius will be. This value is mostly arbitrary, but still effective to the range.",
		options =
		{
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8 (Default)", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
			{description = "11", data = 11},
			{description = "12", data = 12},
			{description = "13", data = 13},
			{description = "14", data = 14},
			{description = "15", data = 15},
			{description = "16 (Very Large)", data = 16},

		},
		default = 8,
	},

	{
		name = "dwellersanitydrain",
		label = "Active Sanity Drain",
		hover = "How much sanity is drained time while the Dweller's Mask is active.",
		options =
		{
			{description = "x0.1", data = 0.1},
			{description = "x0.25", data = 0.25},
			{description = "x0.5", data = 0.5},
			{description = "x0.75", data = 0.75},
			{description = "x1 (Default)", data = 1},
			{description = "x1.5", data = 1.5},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
		},
		default = 1,
	},

	{
		name = "dwellerthreshhold",
		label = "Sanity Threshhold",
		hover = "How much sanity is instantly consumed upon activating the hat. Also prevents activation below this amount.",
		options =
		{
			{description = "0", data = 0},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3 (Default)", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "15", data = 15},
			{description = "20", data = 20},
			{description = "25", data = 25},
			{description = "30", data = 30},
			{description = "50", data = 50},
			{description = "100", data = 100},
		},
		default = 3,
	},

	{
		name = "dwellersanitypenalty",
		label = "Sanity Penalty",
		hover = "How much sanity is taken away when someone within a Dweller Mask's radius is hit while at 1 hp.",
		options =
		{
			{description = "0", data = 0},
			{description = "-1 (Default)", data = -1},
			{description = "-2", data = -2},
			{description = "-3", data = -3},
			{description = "-4", data = -4},
			{description = "-5", data = -5},
			{description = "-10", data = -10},
			{description = "-15", data = -15},
			{description = "-20", data = -20},
			{description = "-25", data = -25},
			{description = "-30", data = -30},
			{description = "-50", data = -50},
			{description = "-100", data = -100},
		},
		default = -1,
	},

	{
		name = "dwellerfuelpenalty",
		label = "Usage Penalty",
		hover = "How much fuel is taken away when someone within a Dweller Mask's radius is hit while at 1 hp.",
		options =
		{
			{description = "0", data = 0},
			{description = "-1 second", data = -2},
			{description = "-2 seconds", data = -4},
			{description = "-3 seconds", data = -6},
			{description = "-4 seconds", data = -8},
			{description = "-5 seconds", data = -10},
			{description = "-10 seconds", data = -20},
			{description = "-15 seconds", data = -30},
			{description = "-20 seconds", data = -40},
			{description = "-25 seconds", data = -50},
			{description = "-30 seconds", data = -60},
			{description = "-60 seconds", data = -120},
			{description = "-2 minutes", data = -240},
		},
		default = -5,
	},

	{
		name = "dwellerhealthpenalty",
		label = "Max Health Penalty Mult",
		hover = "Controls how damage taken and mitigated by the Dweller's Mask is translated to a max health penalty, via a multiplier.",
		options =
		{
			{description = "x0.1", data = 0.1},
			{description = "x0.25", data = 0.25},
			{description = "x0.5 (Default)", data = 0.5},
			{description = "x0.75", data = 0.75},
			{description = "x1", data = 1},
			{description = "x1.5", data = 1.5},
			{description = "x2", data = 2},
		},
		default = 0.5,
	},

	{
		name = "dwellerrevivepenalty",
		label = "Revivee Penalties",
		hover = "Whether or not players revived by the Dweller's Mask will have additional stat penalties, similar to the Telltale Heart's revive penalties.",
		options =
		{
			{description = "Enabled (Default)", data = true},
			{description = "Disabled", data = false},
		},
		default = true,
	},

	{
		name = "dwellerrevivesanity",
		label = "Reviver Sanity Bonus",
		hover = "How much sanity will be restored to Hat Kid when a player is revived by the Dweller's Mask.",
		options =
		{
			{description = "0", data = 0},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "20", data = 20},
			{description = "30", data = 30},
			{description = "40 (Default)", data = 40},
			{description = "80", data = 80},
			{description = "120", data = 120},
		},
		default = 40,
	},

	{
		name = "dwellerrevivefuel",
		label = "Reviver Fuel Usage",
		hover = "How much fuel is taken away from the Dweller's Mask when a player is successfully revived.",
		options =
		{
			{description = "0%", data = 1},
			{description = "-10%", data = 10},
			{description = "-20%", data = 5},
			{description = "-25% (Default)", data = 4},
			{description = "-50%", data = 2},
			{description = "0%", data = 1},
		},
		default = 4,
	},

	{
		name = "dwellervfx",
		label = "Night Vision Screen Effect",
		hover = "Whether or not the screen will turn green while under the influence of the Dweller Mask's night vision.",
		options =
		{
			{description = "Enabled (Default)", data = true},
			{description = "Disabled", data = false},
		},
		default = true,
	},

	{
		name = "Time Stop Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "timestopdurability",
		label = "Durability",
		hover = "How long the Time Stop Hat lasts. Nightmare Fuel refuels 2 uses at all settings.",
		options =
		{
			-- nightmarefuel refules up to 180 regardless of this setting.
			{description = "Forever", data = false},
			{description = "1 use", data = 90},
			{description = "2 uses", data = 180},
			{description = "4 uses", data = 180 * 2},
			{description = "6 uses", data = 180 * 3},
			{description = "8 uses (Default)", data = 180 * 4},
			{description = "10 uses", data = 180 * 5},
			{description = "12 uses", data = 180 * 6},
			{description = "14 uses", data = 180 * 7},
			{description = "20 uses", data = 180 * 10},
			{description = "40 uses", data = 180 * 20},
			{description = "60 uses", data = 180 * 30},
			{description = "Forever", data = false},
		},
		default = 180 * 4,
	},
	
	{
		name = "timestopcooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "4 Seconds", data = 4},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds (Default)", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 60,
	},
	
	{
		name = "timestopactive",
		label = "Duration",
		hover = "How long the Time Stop effect can remain active. It can be cancelled early regardless of what this value is set to.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "12 Seconds", data = 12},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds (Default)", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 20,
	},

	{
		name = "timestopscale",
		label = "Time Speed",
		hover = "The multiplier applied to the speed of various actions, such as attack, and movement speed.",
		options =
		{
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.334", data = 1/3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5 (Default)", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.667", data = 2/3},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
		},
		default = 0.5,
	},
	
	{
		name = "Hatbrella Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "hatbrelladamage",
		label = "Umbrella Damage",
		hover = "How much damage Hat Kid's umbrella deals.",
		options =
		{
			{description = "1", data = 1},
			{description = "10", data = 9},
			{description = "14", data = 14},
			{description = "27", data = 27},
			{description = "34", data = 34},
			{description = "40 (Default)", data = 40},
			{description = "51", data = 51},
			{description = "63", data = 63},
			{description = "72", data = 72},
			{description = "89", data = 89},
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "500", data = 500},
			{description = "KILLER QUEEN!!!", data = 999999, hover = "999,999"},
		},
		default = 40,
	},

	{
		name = "hatbrelladurability",
		label = "Closed Umbrella Durability",
		hover = "How many times you can hit something with the closed variant of Hat Kid's umbrella, before it breaks.",
		options =
		{
			{description = "Disabled", data = false},
			
			{description = "10", data = 10},
			{description = "25", data = 25},
			{description = "50", data = 180},
			{description = "75", data = 75},
			{description = "100", data = 100},
			{description = "125", data = 125},
			{description = "150", data = 150},
			{description = "175", data = 175},
			{description = "200 (Default)", data = 200},
			{description = "250", data = 250},
			{description = "300", data = 300},
			{description = "400", data = 400},
			{description = "500", data = 500},

			{description = "Disabled", data = false},

		},
		default = 200,
	},

	{
		name = "hatbrellaopendurability",
		label = "Open Umbrella Durability",
		hover = "How long Hat Kid's umbrella lasts while open, using in game time.",
		options =
		{
			{description = "Disabled", data = false},
			
			{description = "1 segment", data = seg_time},
			{description = "4 segments", data = seg_time * 4},
			{description = "8 segments", data = seg_time * 8},
			{description = "1 day", data = total_day_time * 1},
			{description = "2 days", data = total_day_time * 2},
			{description = "4 days", data = total_day_time * 4},
			{description = "6 days", data = total_day_time * 6},			
			{description = "8 days (Default)", data = total_day_time * 8},
			{description = "10 days", data = total_day_time * 10},
			{description = "12 days", data = total_day_time * 12},
			{description = "15 days", data = total_day_time * 15},
			{description = "20 days", data = total_day_time * 20},

			{description = "Disabled", data = false},

		},
		default = total_day_time * 8,
	},

	{
		name = "Misc Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
        name = "hatkid_polarhatkey",
        label = "Ability Key",
        hover = "This is the key used to activate hat abilities. Unfortunately this is set globally for all hat kid's, rather than per player.",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z (Default)", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 122,
    },

	{
		name = "funnymode",
		label = "Funny Mode",
		hover = "Causes some intentional glitches. You may not notice an effect.",
		options =
		{
			{description = "Disabled (Default)", data = false},
			{description = "Enabled", data = true},
		},
		default = false,
	},
	
	{
		name = "Experimental",
		options = null_options,
		hover = "",
		default = 0,
	},	

	-- {
	-- 	name = "enablepons",
	-- 	label = "Pons",
	-- 	hover = "Enables the Pon Count Meter, as well as the spawning of Green Pons through various actions (eg. mining, chopping, killing)",
	-- 	options =
	-- 	{
	-- 		{description = "Disabled (Default)", data = false},
	-- 		{description = "Enabled", data = true},
	-- 	},
	-- 	default = false,
	-- },

	-- {
	-- 	name = "ponsmax",
	-- 	label = "Max Pons",
	-- 	hover = "How many Pons Hat Kid can hold at once.",
	-- 	options =
	-- 	{
	-- 		{description = "1,000", data = 1000},
	-- 		{description = "1,500", data = 1500},
	-- 		{description = "2,000", data = 2000},
	-- 		{description = "2,500", data = 2500},
	-- 		{description = "2,500 (Default)", data = 2500},
	-- 		{description = "3,000", data = 3000},
	-- 		{description = "3,500", data = 3500},
	-- 		{description = "4,000", data = 4000},
	-- 		{description = "4,500", data = 4500},
	-- 		{description = "5,000", data = 5000},
	-- 		{description = "10,000", data = 10000},
			

	-- 	},
	-- 	default = 2500,
	-- },
}