name = "Hat Kid Reloaded (Internal)" -- Edit this title depending on branch.
description = "The Overhaul update! So much to do, and so much to try!"
author = "Skylarr"
version = "3.0.0b15"

forumthread = ""

api_version = 10

dst_compatible = true

dont_starve_compatible = false
reign_of_giants_compatible = false

all_clients_require_mod = true 

icon_atlas = "modicon.xml"
icon = "modicon.tex"

server_filter_tags = {
"kid",
"hat",
"time",
"hatkid",
"skylarr",
}

local null_options = {
	{ description = "", data = 0 }
}


configuration_options =
{

	{
		name = "Character Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "hatkidbasehp",
		label = "Health",
		hover = "How much health Hat Kid will have.",
		options =
		{
			{description = "25", data = 25},
			{description = "50", data = 50},
			{description = "75", data = 75},
			{description = "100", data = 100},
			{description = "120 (Default)", data = 120},
			{description = "125", data = 125},
			{description = "150", data = 150},
			{description = "175", data = 175},
			{description = "200", data = 200},
			{description = "225", data = 225},
			{description = "250", data = 250},
			{description = "275", data = 275},				
			{description = "300", data = 300},
		},
		default = 120,
	},
	
	{
		name = "hatkidbasesanity",
		label = "Sanity",
		hover = "How much sanity Hat Kid will have.",
		options =
		{
			{description = "25", data = 25},
			{description = "50", data = 50},
			{description = "75", data = 75},
			{description = "100 (Default)", data = 100},
			{description = "125", data = 125},
			{description = "150", data = 150},
			{description = "175", data = 175},
			{description = "200", data = 200},
			{description = "225", data = 225},
			{description = "250", data = 250},
			{description = "275", data = 275},				
			{description = "300", data = 300},
		},
		default = 100,
	},
	
	{
		name = "hatkidbasehunger",
		label = "Hunger",
		hover = "How much hunger Hat Kid will have.",
		options =
		{
			{description = "25", data = 25},
			{description = "50", data = 50},
			{description = "75", data = 75},
			{description = "100", data = 100},
			{description = "105", data = 105},
			{description = "110", data = 110},
			{description = "115 (Default)", data = 115},
			{description = "120", data = 120},
			{description = "125", data = 125},
			{description = "150", data = 150},
			{description = "175", data = 175},
			{description = "200", data = 200},
			{description = "225", data = 225},
			{description = "250", data = 250},
			{description = "275", data = 275},				
			{description = "300", data = 300},
		},
		default = 115,
	},
	
	{
		name = "hatkidspeed",
		label = "Run Speed",
		hover = "How fast Hat Kid will go.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.1", data = 1.1},
			{description = "x1.2", data = 1.2},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
			{description = "x69 (dear god)", data = 69},
		},
		default = 1,
	},
	
		{
		name = "hatkiddamage",
		label = "Damage",
		hover = "Hat Kid's damage multiplier",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.85 (Default)", data = 0.85},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 0.85,
	},
	
		{
		name = "hatkidbasesize",
		label = "Size Scale",
		hover = "How big Hat Kid will be",
		options =
		{
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.85 (Default)", data = 0.85},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 0.85,
	},
	
	{
		name = "hatkidrate",
		label = "Hunger Rate",
		hover = "How fast Hat Kid's hunger drains.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},
	
	{
		name = "hatkidnightdrain",
		label = "Night Drain",
		hover = "How badly Hat Kid's sanity will be impacted by nighttime.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},

	{
		name = "hatkidsanitydrain",
		label = "Sanity Drain",
		hover = "How badly Hat Kid's sanity will be impacted in general.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1 (Default)", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1,
	},	


	{
		name = "Kid's Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	

	{
		name = "hatkidaurasize",
		label = "Sanity Aura Size",
		hover = "How big Hat Kid's sanity aura will be.",
		options =
		{
			{description = "Disabled", data = 0},
			{description = "Smol", data = 16},
			{description = "Small", data = 32},
			{description = "Medium", data = 64},
			{description = "Large (Default)", data = 128},
			{description = "Huge! (seriously)", data = 512},
			
		},
		default = 128,
	},

	{
		name = "hatkidaurarate",
		label = "Sanity Aura Rate",
		hover = "How powerful Hat Kid's sanity aura is, in sanity per minute",
		options =
		{
			{description = "1", data = 0.0167},
			{description = "1.5", data = 0.025},
			{description = "3 (Default)", data = 0.05},
			{description = "6", data = 0.1},
			{description = "15", data = 0.25},
			{description = "20", data = 0.334},
			{description = "30", data = 0.5},
			{description = "60", data = 1},
			{description = "120", data = 2},
			{description = "240", data = 4},
			{description = "600", data = 10},
		},
		default = 0.05,
	},

	{
		name = "Sprint Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "sprinthatspeedmult",
		label = "Speed Multiplier",
		hover = "How much faster the Sprint Hat makes Hat Kid run.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.1", data = 1.1},
			{description = "x1.25", data = 1.25},
			{description = "x1.3", data = 1.3},
			{description = "x1.35 (Default)", data = 1.35},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1.35,
	},
	
	{
		name = "sprinthathungerburnrate",
		label = "Hunger Multiplier",
		hover = "How much faster the Sprint Hat makes Hat Kid starve, while running.",
		options =
		{
			{description = "x0.001", data = 0.001},
			{description = "x0.01", data = 0.01},
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.6s", data = 1.6},
			{description = "x1.75 (Default)", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
			{description = "x4", data = 4},
			{description = "x5", data = 5},
			{description = "x6", data = 6},
			{description = "x7", data = 7},
			{description = "x8", data = 8},
			{description = "x9", data = 9},
			{description = "x10", data = 10},
		},
		default = 1.75,
	},

	{
		name = "sprinthatsfx",
		label = "Sprint SFX",
		hover = "Whether or not moving while wearing the sprint hat will produce a sound effect. It can be disabled if you find it annoying.",
		options =
		{
			{description = "Disabled", data = false},
			{description = "Enabled (Default)", data = true},
		},
		default = true,
	},

	{
		name = "Brewing Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "brewcooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds (Default)", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 30,
	},
	
	{
		name = "brewcharge",
		label = "Potion Charge Time",
		hover = "How long it takes for the potion to brew before Hat Kid can throw it.",
		options =
		{
			{description = "Instant", data = 0},
			{description = "1/4 of a Second", data = 0.25},
			{description = "1/2 of a Second", data = 0.5},
			{description = "3/4 of a Second", data = 0.75},
			{description = "1 Second (Default)", data = 1},
			{description = "2 Seconds", data = 2},
			{description = "3 Seconds", data = 3},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
		},
		default = 1,
	},
	
	{
		name = "brewslow",
		label = "Potion Charge Slowness",
		hover = "Hat Kid's speed multiplier while holding a potion.",
		options =
		{
			{description = "-100%", data = 0},
			{description = "-90%", data = 0.1},
			{description = "-80%", data = 0.2},
			{description = "-75%", data = 0.25},
			{description = "-70%", data = 0.3},
			{description = "-60%", data = 0.4},
			{description = "-50%", data = 0.5},
			{description = "-40%", data = 0.6},
			{description = "-30%", data = 0.7},
			{description = "-25% (Default)", data = 0.75},
			{description = "-20%", data = 0.8},
			{description = "-10%", data = 0.9},
			{description = "No effect", data = 1},
			{description = "+10%", data = 1.1},
			{description = "+20%", data = 1.2},
			{description = "+30%", data = 1.3},
			{description = "+40%", data = 1.4},
			{description = "+50%", data = 1.5},
			{description = "+60%", data = 1.6},
			{description = "+70%", data = 1.7},
			{description = "+80%", data = 1.8},
			{description = "+90%", data = 1.9},
			{description = "+100%", data = 2},
			{description = "+200%", data = 3},
			{description = "+300%", data = 4},
		},
		default = 0.75,
	},
	
	{
		name = "brewdamage",
		label = "Potion Explosion Damage",
		hover = "How much damage the thrown potion's explosion will deal.",
		options =
		{
			{description = "1", data = 1},
			{description = "9", data = 9},
			{description = "14", data = 14},
			{description = "27", data = 27},
			{description = "34", data = 34},
			{description = "46 (Default)", data = 46},
			{description = "51", data = 51},
			{description = "63", data = 63},
			{description = "72", data = 72},
			{description = "89", data = 89},
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "500", data = 500},
			{description = "KILLER QUEEN!!!", data = 999999, hover = "999,999"},
		},
		default = 46,
	},
	
	{
		name = "brewradius",
		label = "Potion Explosion Radius",
		hover = "How big the thrown potion's explosions will be. This value is mostly arbitrary, but still effective to the range.",
		options =
		{
			{description = "0 (Disabled)", data = 0},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4 (Default)", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8 (Very Large)", data = 8},
		},
		default = 4,
	},

	{
		name = "Ice Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "polarcooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes (Default)", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 120,
	},

	{
		name = "polarlevel",
		label = "Freeze Level",
		hover = "Sets which level of freeze the Ice Hat will use in it's radius. Each level is equivelant to 1 hit from the Ice Staff.",
		options =
		{
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3 (Default)", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 3,
	},

	{
		name = "polartemp",
		label = "Temp Reduction",
		hover = "Determines how much the Ice Hat cools players inside the radius down by when activated.",
		options =
		{
			{description = "None", data = 0},
			{description = "-2.5", data = 2.5},
			{description = "-5", data = 5},
			{description = "-10", data = 10},
			{description = "-15 (Default)", data = 15},
			{description = "-20", data = 20},
			{description = "-25", data = 25},
			{description = "-30", data = 30},
			{description = "-35", data = 35},
			{description = "-40", data = 40},
			{description = "-50", data = 50},
			{description = "-60", data = 60},
			{description = "-70", data = 70},
			{description = "-80", data = 80},
			{description = "-90", data = 90},
			{description = "-100", data = 100},



		},
		default = -15,
	},

	{
		name = "polarradius",
		label = "Radius",
		hover = "How big the Ice Hat's freeze radius will be. This value is mostly arbitrary, but still effective to the range.",
		options =
		{
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7 (Default)", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
			{description = "11", data = 11},
			{description = "12", data = 12},
			{description = "13", data = 13},
			{description = "14", data = 14},
			{description = "15", data = 15},
			{description = "16 (Very Large)", data = 16},

		},
		default = 7,
	},

	{
		name = "Dweller Mask Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "dwellercooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds (Default)", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 90,
	},
	
		{
		name = "dwelleractive",
		label = "Duration",
		hover = "How long the dweller mask can remain active. It can be cancelled early regardless of what this value is set to.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds (Default)", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 30,
	},
	
		{
		name = "dwellerlinger",
		label = "Linger Duration",
		hover = "How long the nightvision effect will linger for.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds (Default)", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 5,
	},

	{
		name = "dwellerradius",
		label = "Radius",
		hover = "How big the Dweller Mask's night vision raidus will be. This value is mostly arbitrary, but still effective to the range.",
		options =
		{
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8 (Default)", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
			{description = "11", data = 11},
			{description = "12", data = 12},
			{description = "13", data = 13},
			{description = "14", data = 14},
			{description = "15", data = 15},
			{description = "16 (Very Large)", data = 16},

		},
		default = 8,
	},

	{
		name = "Time Stop Hat Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "timestopcooldown",
		label = "Cooldown",
		hover = "How long the hat will take to recharge.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes (Default)", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 180,
	},
	
		{
		name = "timestopactive",
		label = "Duration",
		hover = "How long the Time Stop effect can remain active. It can be cancelled early regardless of what this value is set to.",
		options =
		{
			{description = "1 Second", data = 1},
			{description = "5 Seconds", data = 5},
			{description = "10 Seconds", data = 10},
			{description = "12 Seconds (Default)", data = 12},
			{description = "15 Seconds", data = 15},
			{description = "20 Seconds", data = 20},
			{description = "30 Seconds", data = 30},
			{description = "45 Seconds", data = 45},
			{description = "60 Seconds", data = 60},
			{description = "90 Seconds", data = 90},
			{description = "2 Minutes", data = 120},
			{description = "3 Minutes", data = 180},
			{description = "4 Minutes", data = 240},
			{description = "5 Minutes", data = 300},
			{description = "10 Minutes", data = 600},
			{description = "15 Minutes", data = 900},
		},
		default = 12,
	},

	{
		name = "timestopscale",
		label = "Time Speed",
		hover = "The multiplier applied to the speed of various actions, such as attack, and movement speed.",
		options =
		{
			{description = "x0.1", data = 0.1},
			{description = "x0.2", data = 0.2},
			{description = "x0.3", data = 0.3},
			{description = "x0.334 (Default)", data = 0.334},
			{description = "x0.4", data = 0.4},
			{description = "x0.5", data = 0.5},
			{description = "x0.6", data = 0.6},
			{description = "x0.7", data = 0.7},
			{description = "x0.8", data = 0.8},
			{description = "x0.9", data = 0.9},
			{description = "x1", data = 1},
			{description = "x1.25", data = 1.25},
			{description = "x1.5", data = 1.5},
			{description = "x1.75", data = 1.75},
			{description = "x2", data = 2},
			{description = "x3", data = 3},
		},
		default = 0.334,
	},
	
	{
		name = "Hatbrella Options",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
		name = "hatbrelladamage",
		label = "Blue Umbrella Damage",
		hover = "How much damage Hat Kid's umbrella deals.",
		options =
		{
			{description = "1", data = 1},
			{description = "9", data = 9},
			{description = "14", data = 14},
			{description = "27 (Default)", data = 27},
			{description = "34", data = 34},
			{description = "51", data = 51},
			{description = "63", data = 63},
			{description = "72", data = 72},
			{description = "89", data = 89},
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "500", data = 500},
			{description = "KILLER QUEEN!!!", data = 999999, hover = "999,999"},
		},
		default = 27,
	},
	
	{
		name = "hatbrella2damage",
		label = "Red Umbrella Damage",
		hover = "How much damage Hat Kid's Red umbrella deals.",
		options =
		{
			{description = "1", data = 1},
			{description = "9", data = 9},
			{description = "14", data = 14},
			{description = "27", data = 27},
			{description = "34", data = 34},
			{description = "51 (Default)", data = 51},
			{description = "63", data = 63},
			{description = "72", data = 72},
			{description = "89", data = 89},
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "500", data = 500},
			{description = "KILLER QUEEN!!!", data = 999999, hover = "999,999"},
		},
		default		= 51,
	},		

	{
		name = "Ability Option",
		options = null_options,
		hover = "",
		default = 0,
	},	
	
	{
        name = "hatkid_polarhatkey",
        label = "Ability Key",
        hover = "This is the key used to activate hat abilities. Unfortunately this is set globally for all hat kid's, rather than per player.",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z (Default)", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 122,
    },

	{
		name = "funnymode",
		label = "Funny Mode",
		hover = "Introduces intentional glitches that are pretty funny, if maybe a bit overpowered, to play with. Please tell me if you have this enabled while reporting bugs.",
		options =
		{
			{description = "Disabled (Default)", data = false},
			{description = "Enabled", data = true},
		},
		default = false,
	},
}